name: Automated niv-managed dependency updates
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@60f23607814cf4f2e80a1e32ee74f8323897d09e
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          keep_updating: true
          github_changelog_no_backreferences: true


